config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  namespace :user do
    get '/sign_up_submit_email', to: 'emails#new'
    post '/sign_up_submit_email', to: 'emails#create'
  end

  root to: 'questions#index'

  concern :voted do
    member do
      patch :upvote
      patch :downvote
      patch :cancel_vote
    end
  end

  concern :commented do
    resources :comments, only: :create, shallow: true
  end

  resources :questions, concerns: [:voted, :commented] do
    resources :answers, concerns: [:voted, :commented], shallow: true do
      patch :select_best, on: :member
    end
  end

  resources :files, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: :index

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, except: [:new, :edit] do
        resources :answers, shallow: true, only: [:index, :create, :show]
      end
    end
  end

  resources :subscriptions, only: [:create, :destroy]

  resources :searches, only: :index

  mount ActionCable.server => '/cable'

end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_many :subscriptions, dependent: :destroy, as: :subscribable
  has_one :reward, dependent: :destroy, as: :rewardable

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :reward, reject_if: :all_blank, allow_destroy: true

  validates :title, :body, presence: true
  validates :title, length: { in: 10..150 }
  validates :body, length: { minimum: 10 }

  after_create :calculate_reputation

  # при создании вопроса автор автоматически подписывается на уведомления
  after_create :subscribe_author!

  private

  def subscribe_author!
    subscriptions.create!(user: user)
  end

  def calculate_reputation
    ReputationJob.perform_later(self)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController

  skip_authorization_check

  before_action :load_question, only: %i[show update destroy]

  def index
    @questions = Question.all
    render json: @questions
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_resource_owner
    if @question.save
      render json: @question
    else
      render json: @question.errors, status: :unprocessable_entity
    end
  end

  def show
    render json: @question, serializer: QuestionFullSerializer
  end

  def update
    authorize! :update, @question
    if @question.update(question_params)
      render json: @question
    else
      render json: @question.errors, status: :unprocessable_entity
    end
  end

  def destroy
    authorize! :destroy, @question
    @question.destroy
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def load_question
    @question = Question.find(params[:id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_question, only: %i[show destroy update]

  after_action :publish_question, only: [:create]

  authorize_resource

  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
    @question.links.new
    @question.reward = Reward.new
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    reward = @question.reward.present? ? ' Reward was set.' : ''
    if @question.save
      redirect_to @question, notice: "Your question successfully created.#{reward}"
    else
      render :new
    end
  end

  def show
    @answer = @question.answers.new
    @answer.links.new
    gon.question_id = @question.id
    gon.current_user_id = current_user&.id
    gon.question_author_id = @question.user_id
  end

  def destroy
    @question.destroy
    redirect_to questions_path
  end

  def update
    @question.update(question_params)
  end

  private

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast(
          'questions',
          ApplicationController.render(
            partial: 'questions/question.json',
            locals: { question: @question }
          )
        )
  end

  def question_params
    params.require(:question).permit(:title, :body,
                                      files: [], links_attributes: [:name, :url, :_destroy],
                                      reward_attributes: [:name, :picture])
  end

  def load_question
    @question = Question.with_attached_files.find(params[:id])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answer_form.html.slim
.answer-errors
  =render 'shared/errors', resource: @answer

= form_with model: [@question, @answer], class: 'new-answer' do |f|
  p
    = f.label :body
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true

  = render 'shared/add_links', f: f

  p= f.submit 'Write Answer'

app/views/questions/_question.html.slim
-if question.persisted?
  div id="question_id_#{question.id}"
    span id="errors_question_id_#{question.id}"
    = link_to question.title,  question_path(question)
    = render 'shared/files_list', resource: question

    .question
      - if can?(:destroy, question)
          p= button_to 'Delete question', question_path(question), method: :delete
      - if can?(:update, question)
          p= link_to 'Edit question', '#', class: 'edit-question-link', data: { question_id: question.id }
          = render 'questions/question_edit_form', question: question
      hr

app/views/questions/_question_edit_form.html.slim
= form_with model: question, class: 'hidden', html: { id: "edit-question-#{question.id}" } do |f|
  = f.label :title, 'Question title'
  = f.text_field :title
  = f.label :body, 'Question body'
  = f.text_area :body
  = f.label :files
  = f.file_field :files, multiple: true, direct_upload: true

  = render 'shared/edit_files', resource: question
  = render 'shared/links_list', resource: question

  = render 'shared/cocoon_links', f: f

  = f.submit 'Save question'

app/views/questions/_reward_form.html.slim
p Reward:
#reward
  = f.fields_for :reward do |r|
    p
      = r.label :name, 'Reward name'
      = r.text_field :name
    p
      = r.label :picture
      = r.file_field :picture

app/views/questions/index.html.slim
div align="center"
  - if can?(:create, Question)
    = link_to 'Ask question', new_question_path

.questions
  = render @questions

app/views/questions/new.html.slim
=render 'shared/errors', resource: @question

= form_with model: @question, local: true do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true

  = render 'shared/add_links', f: f

  = render 'reward_form', f: f

  p= f.submit 'Ask'

app/views/questions/show.html.slim
h1= @question.title
p= @question.body
p= "Author: #{@question.user.email}"

.subscription
  - if current_user.present?
    = render 'subscriptions/subscribe_link', subscribable: @question

- if can_vote?(@question)
  = render 'shared/vote', resource: @question

- @question.files.each do |file|
  p= link_to file.filename.to_s, url_for(file)

- if can?(:create, Comment)
  .add-comment-question
    = render 'shared/add_comment_form', commentable: @question

.question-comments
  = render 'shared/comments_list', resource: @question

.links
  = render 'shared/links_list', resource: @question

.answers
  = render @question.answers
  hr

- if can?(:create, Answer)
  .add-answer
    p Write answer to the question
    = render 'questions/answer_form'
- else
    p
      = link_to 'Log In', new_user_session_path
      |  in order to write an answer

app/views/questions/update.js.erb
$('#errors_question_id_<%= @question.id %>').html('<%= render 'shared/errors', resource: @question %>');

<% if !@question.errors.present? %>
    $('#question_id_<%= @question.id %>').html('<%= j render @question %>');
<% end %>