config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  namespace :user do
    get '/sign_up_submit_email', to: 'emails#new'
    post '/sign_up_submit_email', to: 'emails#create'
  end

  root to: 'questions#index'

  concern :voted do
    member do
      patch :upvote
      patch :downvote
      patch :cancel_vote
    end
  end

  concern :commented do
    resources :comments, only: :create, shallow: true
  end

  resources :questions, concerns: [:voted, :commented] do
    resources :answers, concerns: [:voted, :commented], shallow: true do
      patch :select_best, on: :member
    end
  end

  resources :files, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: :index

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, except: [:new, :edit] do
        resources :answers, shallow: true, only: [:index, :create, :show]
      end
    end
  end

  resources :subscriptions, only: [:create, :destroy]

  resources :searches, only: :index

  mount ActionCable.server => '/cable'

end

app/views/shared/_add_comment_form.html.slim
div id="comment_errors_#{commentable_label(commentable)}"
  = render 'shared/errors', resource: @comment

= form_with model: [commentable, commentable.comments.new], class: 'new-comment' do |f|
  p
    = f.label :body
    = f.text_area :body

  p= f.submit 'Add comment'

app/views/shared/_add_links.html.slim
p Links:
#links
  = f.fields_for :links do |l|
    = render 'shared/link_fields', f: l
  .add_link
    = link_to_add_association 'add link', f, :links, partial: 'shared/link_fields'

app/views/shared/_cocoon_links.html.slim
p Links:
#links
  = f.fields_for :links do |l|
    = render 'shared/link_fields', f: l
  .add_link
    = link_to_add_association 'add link', f, :links, partial: 'shared/link_fields'

app/views/shared/_comments_list.html.slim
div id="comments_#{commentable_label(resource)}"
  - if resource.comments.any?
    p Comments:
    = render resource.comments

app/views/shared/_edit_files.html.slim
- resource.files.each do |file|
  div id="edit_file_id_#{file.id}"
    p= link_to file.filename.to_s, url_for(file)
    p= link_to 'Delete file', file_path(file), remote: true, method: :delete

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_files_list.html.slim
- resource.files.each do |file|
  div id="file_id_#{file.id}"
    p= link_to file.filename.to_s, url_for(file)

app/views/shared/_link_fields.html.slim
.nested-fields
  p
    = f.label :name, 'Link name'
    = f.text_field :name
  p
    = f.label :url
    = f.text_field :url
  = link_to_remove_association "remove link", f

app/views/shared/_links_list.html.slim
- if resource.links.any?
  p Links:
  ul
    - resource.links.each do |link|
      - if link.persisted?
        div id="link_id_#{link.id}"
          - if link.gist_link?
            li= link.gist_contents
          - else
            li= link_to link.name, link.url
          -if current_user&.author_of?(link.linkable)
            p= link_to 'Delete link', link_path(link), remote: true, method: :delete

app/views/shared/_nav.html.slim
= link_to 'QNA', root_path
span>
= link_to 'Search', searches_path
span>

- if current_user.present?
  = link_to 'Log Out', destroy_user_session_path, method: :delete
  span>
  = link_to 'My Rewards', rewards_path
- else
  = link_to 'Log In', new_user_session_path
  span>
  = link_to 'Sign Up', new_user_registration_path

app/views/shared/_vote.html.slim
.vote
  div id=vote_item_id(resource)
    span id="score_#{vote_item_id(resource)}"
      p= "Rating #{resource.score}"
    | &nbsp;
    = link_to 'Upvote', polymorphic_url([:upvote, resource]), method: :patch, data: { type: :json }, remote: true
    | &nbsp;
    = link_to 'Cancel vote', polymorphic_url([:cancel_vote, resource]), method: :patch, data: { type: :json }, remote: true
    | &nbsp;
    = link_to 'Downvote', polymorphic_url([:downvote, resource]), method: :patch, data: { type: :json }, remote: true