config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  namespace :user do
    get '/sign_up_submit_email', to: 'emails#new'
    post '/sign_up_submit_email', to: 'emails#create'
  end

  root to: 'questions#index'

  concern :voted do
    member do
      patch :upvote
      patch :downvote
      patch :cancel_vote
    end
  end

  concern :commented do
    resources :comments, only: :create, shallow: true
  end

  resources :questions, concerns: [:voted, :commented] do
    resources :answers, concerns: [:voted, :commented], shallow: true do
      patch :select_best, on: :member
    end
  end

  resources :files, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: :index

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, except: [:new, :edit] do
        resources :answers, shallow: true, only: [:index, :create, :show]
      end
    end
  end

  resources :subscriptions, only: [:create, :destroy]

  resources :searches, only: :index

  mount ActionCable.server => '/cable'

end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable

  # new answers are below older, best is on the top
  default_scope { order(best: :desc).order(created_at: :asc) }

  belongs_to :question
  belongs_to :user

  has_many :links, dependent: :destroy, as: :linkable

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  validates :body, presence: true

  after_create :send_notification

  def select_best
    Answer.transaction do
      question.answers.where(best: true).update_all(best: false)
      update!(best: true)
      # изменять статус награды, только если награда была задана автором вопроса
      question.reward.update(user: user) if question.reward
    end
  end

  private

  def send_notification
    NewAnswerNotificationJob.perform_later(question)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!
  before_action :set_question, only: %i[create]
  before_action :set_answer, only: %i[update destroy select_best]

  after_action :publish_answer, only: :create

  authorize_resource

  def new; end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user
    @answer.save
  end

  def destroy
    @answer.destroy
  end

  def update
    @answer.update(answer_params)
    @question = @answer.question
  end

  def select_best
    @answer.select_best
  end

  private

  def publish_answer
    return if @answer.errors.any?
    ActionCable.server.broadcast(
          "answers_of_question_#{@answer.question_id}",
          ApplicationController.render(
            partial: 'answers/answer.json',
            locals: { answer: @answer }
          )
        )
  end

  def set_question
    @question = Question.with_attached_files.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [:name, :url, :_destroy])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController

  authorize_resource class: Answer

  before_action :set_question, only: %i[index create]
  before_action :set_answer, only: %i[show]

  def index
    render json: @question.answers
  end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_resource_owner
    if @answer.save
      render json: @answer
    else
      render json: @answer.errors, status: :unprocessable_entity
    end
  end

  def show
    render json: @answer, serializer: AnswerFullSerializer
  end

  private

  def set_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
  def show_select_best_option?(answer)
    current_user&.author_of?(answer.question) && !answer.best
  end
end

app/views/answers/_answer.html.slim
-if answer.persisted?
  div id="answer_id_#{answer.id}"
    hr
    span id="errors_answer_id_#{answer.id}"
    p= "Answer posted by user #{answer.user.email}"
    p= answer.body
    - if can_vote?(answer)
      = render 'shared/vote', resource: answer
    = render 'shared/files_list', resource: answer
    .links
      = render 'shared/links_list', resource: answer
    - if can?(:select_best, answer)
        p= link_to 'Select as best', select_best_answer_path(answer), remote: true, class: 'select-best', method: :patch
    .delete-answer
      - if can?(:destroy, answer)
        p= link_to 'Delete answer', answer_path(answer), remote: true, method: :delete
    .edit-answer
      - if can?(:update, answer)
        p= link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }
        = render 'answers/answer_edit_form', answer: answer
    .answer-comments
      = render 'shared/comments_list', resource: answer
    - if can?(:create, Comment)
      .add-comment-answer
        = render 'shared/add_comment_form', commentable: answer

app/views/answers/_answer_edit_form.html.slim
= form_with model: answer, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
  = f.label :body, 'Your answer'
  = f.text_area :body
  = f.label :files
  = f.file_field :files, multiple: true, direct_upload: true

  = render 'shared/edit_files', resource: answer
  = render 'shared/cocoon_links', f: f

  = f.submit 'Save'

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>');
  $('.new-answer #answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
$('#answer_id_<%= @answer.id %>').remove();

app/views/answers/select_best.js.erb
$('.answers').html('<%= j render @answer.question.answers %>');

app/views/answers/update.js.erb
$('#errors_answer_id_<%= @answer.id %>').html('<%= render 'shared/errors', resource: @answer %>');

<% if !@answer.errors.present? %>
    $('#answer_id_<%= @answer.id %>').html('<%= j render @answer %>');
<% end %>